name: Deploy Docker

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'Enter the IP address of the remote VM'
        required: true
        
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ./privatekey
          sudo chmod 600 ./privatekey
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/private.key

      - name: SSH into VM and clone repo
        run: |
          echo $SSH_KEY_PATH
          ssh -i ./privatekey ansible@${{ github.event.inputs.ip_address }}<<EOF
            git clone https://github.com/Espesso/SRE-Frontend.git
            git clone https://github.com/Espesso/SRE-Backend-DB.git
            git clone https://github.com/PasitU/SRE-monitoring
            mv ./SRE-monitoring/docker-compose.yaml ./
            sudo docker compose up -d --build
          EOF

      - name: Wait for containers to be up
        run: |
          # SSH into the VM and check if the containers are up
          ssh -i ./privatekey ansible@${{ github.event.inputs.ip_address }} <<'EOF'
            # Expected number of containers (adjust as needed)
            expected_count=3
            max_retries=10
            retries=0

            # Wait loop
            while [ $(docker ps -q | wc -l) -lt $expected_count ]; do
              if [ $retries -ge $max_retries ]; then
                echo "Max retries reached. Not all containers are up."
                exit 1  # Fail the job if max retries are reached
              fi
              echo "Waiting for containers to start... Attempt $((retries+1))/$max_retries"
              retries=$((retries+1))
              sleep 10  # Wait for 10 seconds before checking again
            done

            echo "All containers are up and running!"
          EOF
